version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: green-challenge-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/green_db
#      - SPRING_DATA_MONGODB_URI=mongodb://host.docker.internal:27017/green_db
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: green-challenge-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
