apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: green-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: andrea44/green-challenge:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/green_db"
