name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger only on pushes to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/green-challenge:latest

      # Build and push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/green-frontend:latest

      # Trigger Render backend redeploy
      - name: Trigger Render backend redeploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1fsvqnfte5s73fudptg?key=z9MRDQu6Y9o \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          -H 'Accept: application/json'

      # Trigger Render frontend redeploy
      - name: Trigger Render frontend redeploy
        run: |
          curl -X POST https://api.render.com/deploy/srv-d1ftr42li9vc739vv02g?key=FVwPcpnmj0I \
          -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
          -H 'Accept: application/json'
